### ISSUE TITLE
some confusions and hope to contact you

### ISSUE THREAD

**Issue by lumosity4tpj** [TJU-Zhaoxy/A-Pyramid-Architecture-of-GANs#5]
你好，我最近在复现这篇论文，有几个疑惑的地方能请教你吗，关于数据处理和你未添加的identity loss等，我希望能够联系你的微信或者email。另外，你的尺寸有点问题，主要是因为你未使用ConvTranspose2d的output_padding补维度。

**Comment by TJU-Zhaoxy** [comment]
您好，确有问题存在，感谢您的建议

**Comment by TJU-Zhaoxy** [comment]
您好，此代码确有问题存在，但我已不再研究此论文，抱歉。

**Comment by wang21jun** [comment]
@lumositytpj 同样在复现该paper，方便相互交流下吗？

**Comment by lumositytpj** [comment]
感谢你亲自回复，此代码依然给予我许多帮助。
发件人: TJU-Zhaoxy<mailto:notifications@github.com>
发送时间: 2019年6月18日 14:54
收件人: TJU-Zhaoxy/A-Pyramid-Architecture-of-GANs<mailto:A-Pyramid-Architecture-of-GANs@noreply.github.com>
抄送: lumositytpj<mailto:tangpeijun4@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [TJU-Zhaoxy/A-Pyramid-Architecture-of-GANs] some confusions and hope to contact you (#5)


您好，此代码确有问题存在，但我已不再研究此论文，抱歉。

―

**Comment by lumosity4tpj** [comment]
> 您好，此代码确有问题存在，但我已不再研究此论文，抱歉。

感谢你亲自回复，此代码依然给予我许多帮助。

**Comment by lumosity4tpj** [comment]
> @lumositytpj 同样在复现该paper，方便相互交流下吗？

我的wechat是tangpeijun_142857，你可以备注下
